config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  
  
  root 'fail#index'

  get 'about' => 'fail#about'

  get 'blog' => 'fail#blog'

  get 'contact' => 'fail#contact'

  get 'help' => 'fail#help'

  get 'home' => 'fail#home'

  get 'profile' => 'fail#profile'

  get 'new' => 'fail#new'

  get 'show' => 'fail#show'

  get 'landing' => 'fail#landing'

  get 'edit' => 'fail#edit'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/add_userinfo_to_user.rb
class AddUserinfoToUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fail_controller.rb
class FailController < ApplicationController
  def index
  end

  def about
  end

  def blog
  end

  def contact
  end

  def help
  end

  def home
  end

  def profile
  end

  def new
  end

  def show
  end

  def landing
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fail_helper.rb
module FailHelper
end

app/views/fail/about.html.erb
<h1>Fail#about</h1>
<p>Find me in app/views/fail/about.html.erb</p>

app/views/fail/blog.html.erb
<h1>Fail#blog</h1>
<p>Find me in app/views/fail/blog.html.erb</p>

app/views/fail/contact.html.erb
<h1>Fail#contact</h1>
<p>Find me in app/views/fail/contact.html.erb</p>

app/views/fail/edit.html.erb
<h1>Fail#edit</h1>
<p>Find me in app/views/fail/edit.html.erb</p>

app/views/fail/help.html.erb
<h1>Fail#help</h1>
<p>Find me in app/views/fail/help.html.erb</p>

app/views/fail/home.html.erb
<% if user_signed_in? %>

<div class="row">

	<div class="col-xs-3">
			LEFT
	</div>

	<div class="col-xs-6">
		<div class="panel panel-default">
			CENTER-center-CENTER
		</div>
	</div>
	<div class="col-xs-3">
		RIGHT
	</div>

</div>

<% else %>

	<script type="text/javascript">
		document.location.href ="http://www.echobase.camp"
	</script>




<% end %>

app/views/fail/index.html.erb
<% if !user_signed_in? %>

<div class="row">

	<div class="col-xs-3">

	</div>

	<div class="col-xs-6">
		<div class="panel panel-default">
			<div class="log-in panel">
				
							<%= form_for(:user, :url => session_path(:user)) do |f| %>
							<%= f.label :email %>
							<%= f.text_field :email %><br />
					 		<%= f.label :password %>
							<%= f.password_field :password %><br />
					  		
							<%= f.check_box :remember_me %>
					  		<%= f.label :remember_me %><br />
					  		<%= f.submit 'Sign in' %><br />
					  		<%= link_to "Forgot your password?", new_password_path(:user) %>
							<% end %>
							
						</div>
						<div class="sign-up panel">
				
							<%= form_for(:user, url: registration_path(:user)) do |f| %>

					 		<%= f.label :username %>
					 		<%= f.text_field :username, autofocus: true %><br />
				
					   	<%= f.label :email %>
					   	<%= f.email_field :email %><br />
			
				      	<%= f.label :password %>
				      	<% if @minimum_password_length %>
				      	<em>(<%= @minimum_password_length %> characters minimum)</em>
				      	<% end %>
				      	<%= f.password_field :password, autocomplete: "off" %><br />	
				
				      	<%= f.label :password_confirmation %>
				      	<%= f.password_field :password_confirmation, autocomplete: "off" %><br />	
				
							<%= f.submit "Sign up" %>
			
							<% end %>
					
						</div>
		</div>
	</div>

	<div class="col-xs-3">

	</div>

</div>

<% else %>

	<script type="text/javascript">
		document.location.href ="http://www.echobase.camp/home"
	</script>




<% end %>

app/views/fail/landing.html.erb
<h1>Fail#landing</h1>
<p>Find me in app/views/fail/landing.html.erb</p>

app/views/fail/new.html.erb
<h1>Fail#new</h1>
<p>Find me in app/views/fail/new.html.erb</p>

app/views/fail/profile.html.erb
<h1>Fail#profile</h1>
<p>Find me in app/views/fail/profile.html.erb</p>

app/views/fail/show.html.erb
<h1>Fail#show</h1>
<p>Find me in app/views/fail/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PltfrmX9</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
	  <%= render '/trinkets/nav'%>
	  
	  
     <span class="notice"><%= notice %></span>
     <span class="alert"><%= alert %></span>
	 <div class="container">
    <%= yield %>
  	</div>
  </body>
</html>

app/views/trinkets/_nav.html.erb
<% if !user_signed_in? %>
<%= render 'trinkets/nav_guest' %>
<% else %>
<%= render 'trinkets/nav_user' %>
<% end %>

app/views/trinkets/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">failpractice.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="explore">explore</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
            
            <li role="separator" class="divider"></li>
            <li><a href="help">Help</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/trinkets/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">failpractice.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="home">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="profile">Profile</a></li>
        
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="help">Help</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <li role="separator" class="divider"></li>
            <li><a href="help">Help</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/trinkets/nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">failpractice.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="home">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="profile">profile</a></li>
        
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
            <li><a href="/users/sign_out">Sign Out</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="help">Help</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>